config/routes.rb
Rails.application.routes.draw do
  resources :backpacks do
    get 'new_item_form', on: :member
    post 'add_item',     on: :member
  end
  resources :items
  root 'backpacks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backpack.rb
class Backpack < ApplicationRecord
  has_many :slots, dependent: :destroy
  has_many :items, through: :slots
  validates_presence_of :capacity, :weight_limit
  validates :capacity, :weight_limit, numericality: { greater_than: 0 }

  def add(item)
    return if cant_fit?(item)

    if items.include?(item)
      slot_with(item).increase_quantity
    else
      slots.create(quantity: 1, item_id: item.id)
    end
  end

  def validates_availability_for(item)
    return unless cant_fit?(item)

    errors.add(:capacity, 'This Item Cannot Fit Into This Backpack')
  end

  def available_capacity
    capacity - slots.sum(&:size)
  end

  def overweight?
    slots.sum(&:weight) > weight_limit
  end

  def quantity(item)
    return 0 unless slot_with(item)

    slot_with(item).quantity
  end

  private

  def slot_with(item)
    slots.detect { |slot| slot.item == item }
  end

  def cant_fit?(item)
    item.size > available_capacity
  end
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :name, :size, :weight
  validates :size, :weight, numericality: { greater_than: 0 }

  def to_s
    "#{name} (size: #{size} weight: #{weight})"
  end
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :backpack
  belongs_to :item
  validates_presence_of :quantity

  def increase_quantity
    update_attribute(:quantity, quantity + 1)
  end

  def size
    quantity * item.size
  end

  def weight
    quantity * item.weight
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/backpacks_controller.rb
class BackpacksController < ApplicationController
  before_action :set_backpack,
                only: %i[show edit update destroy add_item new_item_form]

  def new_item_form; end

  def add_item
    item = Item.find(params[:item_id])
    @backpack.validates_availability_for(item)
    if @backpack.errors.empty?
      @backpack.add(item)
      redirect_to @backpack, notice: 'Item was successfully added.'
    else
      render :new_item_form
    end
  end

  def index
    @backpacks = Backpack.all
  end

  def show; end

  def new
    @backpack = Backpack.new
  end

  def edit; end

  def create
    @backpack = Backpack.new(backpack_params)
    if @backpack.save
      redirect_to @backpack, notice: 'Backpack was successfully created.'
    else
      render :new
    end
  end

  def update
    if @backpack.update(backpack_params)
      redirect_to @backpack, notice: 'Backpack was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @backpack.destroy
    redirect_to backpacks_url, notice: 'Backpack was successfully destroyed.'
  end

  private

  def set_backpack
    @backpack = Backpack.find(params[:id])
  end

  def backpack_params
    params.require(:backpack).permit(:capacity, :weight_limit)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  def index
    @items = Item.all
  end

  def show; end

  def new
    @item = Item.new
  end

  def edit; end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :size, :weight)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_validations_errors.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(resource.errors.count, "error") %>
      prohibited this resource from being saved:
    </h2>

    <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/backpacks/_form.html.erb
<%= form_with(model: backpack, local: true) do |form| %>
  <%= render 'validations_errors', resource: backpack %>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity %>
  </div>

  <div class="field">
    <%= form.label :weight_limit %>
    <%= form.number_field :weight_limit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/backpacks/edit.html.erb
<h1>Editing Backpack</h1>

<%= render 'form', backpack: @backpack %>

<%= link_to 'Show', @backpack %> |
<%= link_to 'Back', backpacks_path %>

app/views/backpacks/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Go to Items', items_path %>
<h1>Backpacks</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Capacity</th>
      <th>Weight Limit</th>
      <th>Items</th>
      <th>Available Space</th>
      <th>Overweight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @backpacks.each do |backpack| %>
      <tr>
        <td><%= backpack.id %></td>
        <td><%= backpack.capacity %></td>
        <td><%= backpack.weight_limit %></td>
        <td><%= backpack.slots.count %></td>
        <td><%= backpack.available_capacity %></td>
        <td><%= backpack.overweight? %></td>
        <td><%= link_to 'Show Items', backpack %></td>
        <td><%= link_to 'Edit', edit_backpack_path(backpack) %></td>
        <td><%= link_to 'Destroy', backpack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Backpack', new_backpack_path %>

app/views/backpacks/new.html.erb
<h1>New Backpack</h1>

<%= render 'form', backpack: @backpack %>

<%= link_to 'Back', backpacks_path %>

app/views/backpacks/new_item_form.html.erb
<h1>Add Item to Backpack <%= @backpack.id %> </h1>
<%= form_tag(controller: 'backpacks', action: 'add_item', method: 'post') do %>
  <%= render 'validations_errors', resource: @backpack %>
  <%= label_tag(:item_id, 'Item') %>
  <%= select_tag(:item_id, options_from_collection_for_select(Item.all,
                                                              :id,
                                                              :to_s,
                                                              params[:item_id])
                ) %>
  <%= submit_tag('Add Item') %>
<% end %>

<%= link_to 'Return', @backpack %>

app/views/backpacks/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Backpack <%= @backpack.id %> </h1>

<p>
  <strong>Capacity:</strong>
  <%= @backpack.capacity %>
</p>

<p>
  <strong>Weight Limit:</strong>
  <%= @backpack.weight_limit %>
</p>

<p>
  <strong>Available Space:</strong>
  <%= @backpack.available_capacity %>
</p>

<p>
  <strong>Overweight:</strong>
  <%= @backpack.overweight? %>
</p>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>Size</th>
      <th>Weight</th>
    </tr>
  </thead>

  <tbody>
    <% @backpack.slots.each do |slot| %>
      <tr>
        <td><%= slot.item %></td>
        <td><%= slot.quantity %></td>
        <td><%= slot.size %></td>
        <td><%= slot.weight %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add Item', new_item_form_backpack_path(@backpack) %> |
<%= link_to 'Edit', edit_backpack_path(@backpack) %> |
<%= link_to 'Back', backpacks_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <%= render 'validations_errors', resource: item %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Go to Backpacks', backpacks_path %>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.size %></td>
        <td><%= item.weight %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @item.size %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @item.weight %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBackpack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>